### ISSUE TITLE
简书上最后提到的url

### ISSUE THREAD

**Issue by dogourd** [Honlan/DataVis-Chain#1]
最后那个url好像变了  和你截图不一样。 请问有新的url地址吗

**Comment by dogourd** [comment]
九千多条就没了

**Comment by Honlan** [comment]
这个项目是两三年之前的，所以url现在变了很正常，关键是要学会方法，知道怎么找数据

**Comment by dogourd** [comment]
@Honlan 现在有什么方便的网站吗？ 豆瓣（九千多条没了），猫眼（两千多条没了）
现在了解有什么方便爬的电影网站吗？谢谢
